language: go
go:
  - master

install:
  - go get github.com/gohugoio/hugo

script:
  - hugo

deploy:
  local_dir: public
  repo: hueypark/hueypark.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: jaewan.huey.park@gmail.com
  name: "Jaewan Park"
  on:
    branch: gh-pages
