title: Marsettler
description: Jaewan Park's blog
show_downloads: false
google_analytics: UA-121966234-1
theme: jekyll-theme-hacker
author: 박재완
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
collections:
  tags:
    output: true
    permalink: /tags/:path/
excerpt_separator: <!--more-->
defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
